# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textAnalyzerDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 572)
        MainWindow.setMinimumSize(QtCore.QSize(852, 572))
        MainWindow.setMaximumSize(QtCore.QSize(852, 572))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/FormIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:#f2f2f2")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_detail = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_detail.setGeometry(QtCore.QRect(0, 300, 851, 241))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_detail.setFont(font)
        self.gb_detail.setStyleSheet("color:#262626;")
        self.gb_detail.setObjectName("gb_detail")
        self.btn_analyze = QtWidgets.QPushButton(self.gb_detail)
        self.btn_analyze.setGeometry(QtCore.QRect(30, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_analyze.setFont(font)
        self.btn_analyze.setStyleSheet("border:1px solid #999999;\n"
"border-radius:7px;\n"
"box-sizing: border-box;\n"
"text-decoration:none;\n"
"color:#262626;\n"
"background-color: #cccccc;\n"
" ")
        self.btn_analyze.setObjectName("btn_analyze")
        self.cb_numberRemover = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_numberRemover.setGeometry(QtCore.QRect(20, 100, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_numberRemover.setFont(font)
        self.cb_numberRemover.setStyleSheet("color:#262626;")
        self.cb_numberRemover.setObjectName("cb_numberRemover")
        self.cb_removepunc = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_removepunc.setGeometry(QtCore.QRect(150, 40, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_removepunc.setFont(font)
        self.cb_removepunc.setStyleSheet("color:#262626;")
        self.cb_removepunc.setObjectName("cb_removepunc")
        self.cb_stopwords = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_stopwords.setGeometry(QtCore.QRect(150, 60, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_stopwords.setFont(font)
        self.cb_stopwords.setStyleSheet("color:#262626;")
        self.cb_stopwords.setObjectName("cb_stopwords")
        self.cb_spaceremover = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_spaceremover.setGeometry(QtCore.QRect(150, 80, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_spaceremover.setFont(font)
        self.cb_spaceremover.setStyleSheet("color:#262626;")
        self.cb_spaceremover.setObjectName("cb_spaceremover")
        self.btn_clear = QtWidgets.QPushButton(self.gb_detail)
        self.btn_clear.setGeometry(QtCore.QRect(170, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("border:1px solid #999999;\n"
"border-radius:7px;\n"
"box-sizing: border-box;\n"
"text-decoration:none;\n"
"color:#262626;\n"
"background-color:#cccccc;\n"
" ")
        self.btn_clear.setObjectName("btn_clear")
        self.cb_takedates = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_takedates.setGeometry(QtCore.QRect(20, 80, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_takedates.setFont(font)
        self.cb_takedates.setStyleSheet("color:#262626;")
        self.cb_takedates.setObjectName("cb_takedates")
        self.cb_topicanalysis = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_topicanalysis.setGeometry(QtCore.QRect(20, 130, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_topicanalysis.setFont(font)
        self.cb_topicanalysis.setStyleSheet("color:#262626;")
        self.cb_topicanalysis.setObjectName("cb_topicanalysis")
        self.gb_sentiment = QtWidgets.QCheckBox(self.gb_detail)
        self.gb_sentiment.setGeometry(QtCore.QRect(20, 150, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_sentiment.setFont(font)
        self.gb_sentiment.setStyleSheet("color:#262626;")
        self.gb_sentiment.setObjectName("gb_sentiment")
        self.cb_uppercase = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_uppercase.setGeometry(QtCore.QRect(20, 40, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_uppercase.setFont(font)
        self.cb_uppercase.setStyleSheet("color:#262626;")
        self.cb_uppercase.setObjectName("cb_uppercase")
        self.cb_lowercase = QtWidgets.QCheckBox(self.gb_detail)
        self.cb_lowercase.setGeometry(QtCore.QRect(20, 60, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_lowercase.setFont(font)
        self.cb_lowercase.setStyleSheet("color:#262626;")
        self.cb_lowercase.setObjectName("cb_lowercase")
        self.txt_autodetails = QtWidgets.QTextEdit(self.gb_detail)
        self.txt_autodetails.setGeometry(QtCore.QRect(330, 20, 241, 191))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_autodetails.setFont(font)
        self.txt_autodetails.setStyleSheet("border:1px solid #999999;\n"
"border-radius:7px;")
        self.txt_autodetails.setObjectName("txt_autodetails")
        self.label = QtWidgets.QLabel(self.gb_detail)
        self.label.setGeometry(QtCore.QRect(130, 130, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#262626;")
        self.label.setObjectName("label")
        self.txt_manualdetails = QtWidgets.QTextEdit(self.gb_detail)
        self.txt_manualdetails.setGeometry(QtCore.QRect(590, 20, 241, 191))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_manualdetails.setFont(font)
        self.txt_manualdetails.setStyleSheet("border:1px solid #999999;\n"
"border-radius:7px;")
        self.txt_manualdetails.setObjectName("txt_manualdetails")
        self.gb_text = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_text.setGeometry(QtCore.QRect(0, 0, 841, 301))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_text.setFont(font)
        self.gb_text.setStyleSheet("color:#262626;")
        self.gb_text.setObjectName("gb_text")
        self.txt_rawtext = QtWidgets.QTextEdit(self.gb_text)
        self.txt_rawtext.setGeometry(QtCore.QRect(10, 20, 821, 151))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_rawtext.setFont(font)
        self.txt_rawtext.setStyleSheet("border:1px solid #999999;\n"
"border-radius:7px;")
        self.txt_rawtext.setObjectName("txt_rawtext")
        self.txt_cleantext = QtWidgets.QTextEdit(self.gb_text)
        self.txt_cleantext.setGeometry(QtCore.QRect(10, 210, 821, 81))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_cleantext.setFont(font)
        self.txt_cleantext.setStyleSheet("border:1px solid #999999;\n"
"border-radius:7px;")
        self.txt_cleantext.setObjectName("txt_cleantext")
        self.btn_voice = QtWidgets.QPushButton(self.gb_text)
        self.btn_voice.setGeometry(QtCore.QRect(10, 170, 31, 31))
        self.btn_voice.setAutoFillBackground(False)
        self.btn_voice.setStyleSheet("\n"
"border-radius:10px;\n"
"box-sizing: border-box;\n"
"text-decoration:none;\n"
"color:#400080;\n"
"background-color:#cccccc;\n"
" ")
        self.btn_voice.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/MicIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_voice.setIcon(icon1)
        self.btn_voice.setIconSize(QtCore.QSize(25, 25))
        self.btn_voice.setObjectName("btn_voice")
        self.btn_addfile = QtWidgets.QPushButton(self.gb_text)
        self.btn_addfile.setGeometry(QtCore.QRect(800, 170, 31, 31))
        self.btn_addfile.setStyleSheet("border-radius:8px;\n"
"box-sizing: border-box;\n"
"text-decoration:none;\n"
"background-color: #cccccc;\n"
" ")
        self.btn_addfile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/FileIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_addfile.setIcon(icon2)
        self.btn_addfile.setIconSize(QtCore.QSize(25, 25))
        self.btn_addfile.setObjectName("btn_addfile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Analyzer"))
        self.gb_detail.setTitle(_translate("MainWindow", " Choose what your options"))
        self.btn_analyze.setText(_translate("MainWindow", "Analyze"))
        self.cb_numberRemover.setText(_translate("MainWindow", "Number Remover"))
        self.cb_removepunc.setText(_translate("MainWindow", "Remove Punctuations"))
        self.cb_stopwords.setText(_translate("MainWindow", "Stop Words Remover"))
        self.cb_spaceremover.setText(_translate("MainWindow", "Extra Space Remover"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.cb_takedates.setText(_translate("MainWindow", "Take Dates"))
        self.cb_topicanalysis.setText(_translate("MainWindow", "Topic Analysis"))
        self.gb_sentiment.setText(_translate("MainWindow", "Emotion Analysis"))
        self.cb_uppercase.setText(_translate("MainWindow", "Upper Case"))
        self.cb_lowercase.setText(_translate("MainWindow", "Lower Case"))
        self.label.setText(_translate("MainWindow", "(Might take long time)"))
        self.gb_text.setTitle(_translate("MainWindow", "Enter your text"))
        self.txt_rawtext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Malgun Gothic\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.txt_cleantext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Malgun Gothic\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
